#!/bin/bash
set -e

export PGPASSWORD=$POSTGRES_PASSWORD;

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $FEAKTION_DB_USER WITH PASSWORD '$FEAKTION_DB_PASS';
  CREATE DATABASE $FEAKTION_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $FEAKTION_DB_NAME TO $FEAKTION_DB_USER;
EOSQL