version: '3'

services:
    node:
        image: node
        restart: always
        container_name: server
        build:
            context: ./docker
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/app
        ports:
            - 3000:3000
    db:
        image: postgres
        restart: always
        container_name: pgsql
        volumes: 
            - ./sql/Feaktion.sql:/sql/Fiction.sql
            - ./dbdata:/var/lib/postgresql/dbdata
        environment:
            POSTGRES_PASSWORD: fiction1234!
            POSTGRES_DB: fiction_main
        ports:
            - 15432:5432

    adminer:
        image: adminer
        restart: always
        container_name: pstgadmin
        ports:
            - 8080:8080