version: '3'

networks: 
    backend:
        driver: bridge

services:
    node:
        image: node
        restart: always
        container_name: node
        build:
            context: ./docker
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/app
        ports:
            - 3000:3000
        networks:
            - backend
    db:
        image: postgres
        restart: always
        container_name: pgsql
        volumes: 
            - ./dbdata:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: fiction1234!
            POSTGRES_DB: fiction_main
        ports:
            - 5432:5432
        networks: 
            - backend

    adminer:
        image: adminer
        restart: always
        container_name: pstgadmin
        ports:
            - 8080:8080
        networks: 
            - backend
    nginx:
        container_name: nginx
        restart: always
        image: nginx:latest
        volumes: 
        - ./nginx/cert:/ssl
        - ./nginx/server.conf:/etc/nginx/nginx.conf
        ports:
        - 443:443
        - 80:80
        networks:
        - backend
        depends_on:
        - node